# Generated by Django 5.1.4 on 2024-12-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('quantity_in_stock', models.PositiveIntegerField()),
                ('reorder_level', models.PositiveIntegerField()),
                ('supplier', models.CharField(max_length=255)),
                ('last_restocked', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
